require: rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'node_modules/**/*'
  TargetRubyVersion:                   2.6
Metrics/LineLength:
  Max:                                 120
Metrics/BlockLength:
  Enabled:                            false
Metrics/MethodLength:
  Max:                                 25
Metrics/AbcSize:
  Max:                                 50
Metrics/ClassLength:
  Enabled:                             false
Style/Documentation:
  Enabled:                             false
Layout/ParameterAlignment:
  EnforcedStyle:                       with_fixed_indentation
Layout/MultilineMethodCallIndentation:
  EnforcedStyle:                       indented
Layout/DotPosition:
  EnforcedStyle:                       trailing
Layout/MultilineHashBraceLayout:
  Enabled:                             false
Style/Lambda:
  Enabled:                             false
Style/CharacterLiteral:
  Enabled:                             false
Style/ClassAndModuleChildren:
  Enabled:                             false
Style/FrozenStringLiteralComment:
  Enabled:                             false
